package com

import (
	"reflect"

	"github.com/Avanis-GmbH/SUC/model"
)

// Returns the segment of the path that is used to identify the resource.
func (c *Client) getSegment(v interface{}) string {
	// If v is a pointer, get the value it points to.
	if reflect.TypeOf(v).Kind() == reflect.Ptr {
		v = reflect.ValueOf(v).Elem().Interface()
	}

	switch v.(type) {
	case model.AclRole:
		return "acl-role"
	case model.AclUserRole:
		return "acl-user-role"
	case model.AppActionButtonTranslation:
		return "app-action-button-translation"
	case model.AppActionButton:
		return "app-action-button"
	case model.AppCmsBlockTranslation:
		return "app-cms-block-translation"
	case model.AppCmsBlock:
		return "app-cms-block"
	case model.AppPaymentMethod:
		return "app-payment-method"
	case model.AppTemplate:
		return "app-template"
	case model.AppTranslation:
		return "app-translation"
	case model.App:
		return "app"
	case model.CategoryTag:
		return "category-tag"
	case model.CategoryTranslation:
		return "category-translation"
	case model.Category:
		return "category"
	case model.CmsBlock:
		return "cms-block"
	case model.CmsPageTranslation:
		return "cms-page-translation"
	case model.CmsPage:
		return "cms-page"
	case model.CmsSection:
		return "cms-section"
	case model.CmsSlotTranslation:
		return "cms-slot-translation"
	case model.CmsSlot:
		return "cms-slot"
	case model.CountryStateTranslation:
		return "country-state-translation"
	case model.CountryState:
		return "country-state"
	case model.CountryTranslation:
		return "country-translation"
	case model.Country:
		return "country"
	case model.CurrencyCountryRounding:
		return "currency-country-rounding"
	case model.CurrencyTranslation:
		return "currency-translation"
	case model.Currency:
		return "currency"
	case model.CustomFieldSetRelation:
		return "custom-field-set-relation"
	case model.CustomFieldSet:
		return "custom-field-set"
	case model.CustomField:
		return "custom-field"
	case model.CustomerAddress:
		return "customer-address"
	case model.CustomerGroupRegistrationSalesChannels:
		return "customer-group-registration-sales-channels"
	case model.CustomerGroupTranslation:
		return "customer-group-translation"
	case model.CustomerGroup:
		return "customer-group"
	case model.CustomerRecovery:
		return "customer-recovery"
	case model.CustomerTag:
		return "customer-tag"
	case model.CustomerWishlistProduct:
		return "customer-wishlist-product"
	case model.CustomerWishlist:
		return "customer-wishlist"
	case model.Customer:
		return "customer"
	case model.DeadMessage:
		return "dead-message"
	case model.DeliveryTimeTranslation:
		return "delivery-time-translation"
	case model.DeliveryTime:
		return "delivery-time"
	case model.DocumentBaseConfigSalesChannel:
		return "document-base-config-sales-channel"
	case model.DocumentBaseConfig:
		return "document-base-config"
	case model.DocumentTypeTranslation:
		return "document-type-translation"
	case model.DocumentType:
		return "document-type"
	case model.Document:
		return "document"
	case model.EventActionRule:
		return "event-action-rule"
	case model.EventActionSalesChannel:
		return "event-action-sales-channel"
	case model.EventAction:
		return "event-action"
	case model.FlowSequence:
		return "flow-sequence"
	case model.Flow:
		return "flow"
	case model.ImportExportFile:
		return "import-export-file"
	case model.ImportExportLog:
		return "import-export-log"
	case model.ImportExportProfileTranslation:
		return "import-export-profile-translation"
	case model.ImportExportProfile:
		return "import-export-profile"
	case model.IntegrationRole:
		return "integration-role"
	case model.Integration:
		return "integration"
	case model.LandingPageSalesChannel:
		return "landing-page-sales-channel"
	case model.LandingPage:
		return "landing-page"
	case model.Language:
		return "language"
	case model.LocaleTranslation:
		return "locale-translation"
	case model.Locale:
		return "locale"
	case model.LogEntry:
		return "log-entry"
	case model.MailHeaderFooterTranslation:
		return "mail-header-footer-translation"
	case model.MailHeaderFooter:
		return "mail-header-footer"
	case model.MailTemplateMedia:
		return "mail-template-media"
	case model.MailTemplateTranslation:
		return "mail-template-translation"
	case model.MailTemplateTypeTranslation:
		return "mail-template-type-translation"
	case model.MailTemplateType:
		return "mail-template-type"
	case model.MailTemplate:
		return "mail-template"
	case model.MainCategory:
		return "main-category"
	case model.MediaDefaultFolder:
		return "media-default-folder"
	case model.MediaFolderConfigurationMediaThumbnailSize:
		return "media-folder-configuration-media-thumbnail-size"
	case model.MediaFolderConfiguration:
		return "media-folder-configuration"
	case model.MediaFolder:
		return "media-folder"
	case model.MediaTag:
		return "media-tag"
	case model.MediaThumbnailSize:
		return "media-thumbnail-size"
	case model.MediaThumbnail:
		return "media-thumbnail"
	case model.MediaTranslation:
		return "media-translation"
	case model.Media:
		return "media"
	case model.MessageQueueStats:
		return "message-queue-stats"
	case model.NewsletterRecipientTag:
		return "newsletter-recipient-tag"
	case model.NewsletterRecipient:
		return "newsletter-recipient"
	case model.Notification:
		return "notification"
	case model.NumberRangeSalesChannel:
		return "number-range-sales-channel"
	case model.NumberRangeState:
		return "number-range-state"
	case model.NumberRangeTypeTranslation:
		return "number-range-type-translation"
	case model.NumberRangeType:
		return "number-range-type"
	case model.NumberRange:
		return "number-range"
	case model.OrderAddress:
		return "order-address"
	case model.OrderCustomer:
		return "order-customer"
	case model.OrderDeliveryPosition:
		return "order-delivery-position"
	case model.OrderDelivery:
		return "order-delivery"
	case model.OrderLineItem:
		return "order-line-item"
	case model.OrderTag:
		return "order-tag"
	case model.OrderTransaction:
		return "order-transaction"
	case model.Order:
		return "order"
	case model.PaymentMethodTranslation:
		return "payment-method-translation"
	case model.PaymentMethod:
		return "payment-method"
	case model.PluginTranslation:
		return "plugin-translation"
	case model.Plugin:
		return "plugin"
	case model.ProductCategoryTree:
		return "product-category-tree"
	case model.ProductCategory:
		return "product-category"
	case model.ProductConfiguratorSetting:
		return "product-configurator-setting"
	case model.ProductCrossSellingAssignedProducts:
		return "product-cross-selling-assigned-products"
	case model.ProductCrossSellingTranslation:
		return "product-cross-selling-translation"
	case model.ProductCrossSelling:
		return "product-cross-selling"
	case model.ProductCustomFieldSet:
		return "product-custom-field-set"
	case model.ProductExport:
		return "product-export"
	case model.ProductFeatureSetTranslation:
		return "product-feature-set-translation"
	case model.ProductFeatureSet:
		return "product-feature-set"
	case model.ProductKeywordDictionary:
		return "product-keyword-dictionary"
	case model.ProductManufacturerTranslation:
		return "product-manufacturer-translation"
	case model.ProductManufacturer:
		return "product-manufacturer"
	case model.ProductMedia:
		return "product-media"
	case model.ProductOption:
		return "product-option"
	case model.ProductPrice:
		return "product-price"
	case model.ProductProperty:
		return "product-property"
	case model.ProductReview:
		return "product-review"
	case model.ProductSearchConfigField:
		return "product-search-config-field"
	case model.ProductSearchConfig:
		return "product-search-config"
	case model.ProductSearchKeyword:
		return "product-search-keyword"
	case model.ProductSortingTranslation:
		return "product-sorting-translation"
	case model.ProductSorting:
		return "product-sorting"
	case model.ProductStreamFilter:
		return "product-stream-filter"
	case model.ProductStreamMapping:
		return "product-stream-mapping"
	case model.ProductStreamTranslation:
		return "product-stream-translation"
	case model.ProductStream:
		return "product-stream"
	case model.ProductTag:
		return "product-tag"
	case model.ProductTranslation:
		return "product-translation"
	case model.ProductVisibility:
		return "product-visibility"
	case model.Product:
		return "product"
	case model.PromotionCartRule:
		return "promotion-cart-rule"
	case model.PromotionDiscountPrices:
		return "promotion-discount-prices"
	case model.PromotionDiscountRule:
		return "promotion-discount-rule"
	case model.PromotionDiscount:
		return "promotion-discount"
	case model.PromotionIndividualCode:
		return "promotion-individual-code"
	case model.PromotionOrderRule:
		return "promotion-order-rule"
	case model.PromotionPersonaCustomer:
		return "promotion-persona-customer"
	case model.PromotionPersonaRule:
		return "promotion-persona-rule"
	case model.PromotionSalesChannel:
		return "promotion-sales-channel"
	case model.PromotionSetgroupRule:
		return "promotion-setgroup-rule"
	case model.PromotionSetgroup:
		return "promotion-setgroup"
	case model.PromotionTranslation:
		return "promotion-translation"
	case model.Promotion:
		return "promotion"
	case model.PropertyGroupOptionTranslation:
		return "property-group-option-translation"
	case model.PropertyGroupOption:
		return "property-group-option"
	case model.PropertyGroupTranslation:
		return "property-group-translation"
	case model.PropertyGroup:
		return "property-group"
	case model.RuleCondition:
		return "rule-condition"
	case model.Rule:
		return "rule"
	case model.SalesChannelAnalytics:
		return "sales-channel-analytics"
	case model.SalesChannelCountry:
		return "sales-channel-country"
	case model.SalesChannelCurrency:
		return "sales-channel-currency"
	case model.SalesChannelDomain:
		return "sales-channel-domain"
	case model.SalesChannelLanguage:
		return "sales-channel-language"
	case model.SalesChannelPaymentMethod:
		return "sales-channel-payment-method"
	case model.SalesChannelShippingMethod:
		return "sales-channel-shipping-method"
	case model.SalesChannelTypeTranslation:
		return "sales-channel-type-translation"
	case model.SalesChannelType:
		return "sales-channel-type"
	case model.SalesChannelTranslation:
		return "sales-channel-translation"
	case model.SalesChannel:
		return "sales-channel"
	case model.SalutationTranslation:
		return "salutation-translation"
	case model.Salutation:
		return "salutation"
	case model.ScheduledTask:
		return "scheduled-task"
	case model.Script:
		return "script"
	case model.SeoUrlTemplate:
		return "seo-url-template"
	case model.SeoUrl:
		return "seo-url"
	case model.ShippingMethodPrice:
		return "shipping-method-price"
	case model.ShippingMethodTag:
		return "shipping-method-tag"
	case model.ShippingMethodTranslation:
		return "shipping-method-translation"
	case model.ShippingMethod:
		return "shipping-method"
	case model.SnippetSet:
		return "snippet-set"
	case model.Snippet:
		return "snippet"
	case model.StateMachineHistory:
		return "state-machine-history"
	case model.StateMachineStateTranslation:
		return "state-machine-state-translation"
	case model.StateMachineState:
		return "state-machine-state"
	case model.StateMachineTransition:
		return "state-machine-transition"
	case model.StateMachineTranslation:
		return "state-machine-translation"
	case model.StateMachine:
		return "state-machine"
	case model.SystemConfig:
		return "system-config"
	case model.Tag:
		return "tag"
	case model.TaxRuleTypeTranslation:
		return "tax-rule-type-translation"
	case model.TaxRuleType:
		return "tax-rule-type"
	case model.TaxRule:
		return "tax-rule"
	case model.Tax:
		return "tax"
	case model.ThemeMedia:
		return "theme-media"
	case model.ThemeSalesChannel:
		return "theme-sales-channel"
	case model.ThemeTranslation:
		return "theme-translation"
	case model.Theme:
		return "theme"
	case model.UnitTranslation:
		return "unit-translation"
	case model.Unit:
		return "unit"
	case model.UserAccessKey:
		return "user-access-key"
	case model.UserConfig:
		return "user-config"
	case model.UserRecovery:
		return "user-recovery"
	case model.User:
		return "user"
	case model.VersionCommitData:
		return "version-commit-data"
	case model.Version:
		return "version"
	case model.WebhookEventLog:
		return "webhook-event-log"
	case model.Webhook:
		return "webhook"
	}

	return "unknown"
}
